
-- MySQL Script generated by MySQL Workbench
-- 08/09/19 22:38:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward EngineeringC:\Users\HJ\Desktop\Project\Project_git_workplace\Portfolio\src\main\resources\portfolio.sql



SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`admin` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`fundManager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`fundManager` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`fundManager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `balance` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`instrument` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`instrument` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(30) NULL,
  `type` ENUM('Bonds', 'Stocks', 'Futures', 'ETFs') NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`hold`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`hold` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`hold` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `volume` INT NULL,
  `instrument_id` INT NOT NULL,
  `fundManager_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Hold_Instrument_idx` (`instrument_id` ASC),
  INDEX `fk_Hold_FundManager1_idx` (`fundManager_id` ASC),
  CONSTRAINT `fk_Hold_Instrument`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `portfolio`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hold_FundManager1`
    FOREIGN KEY (`fundManager_id`)
    REFERENCES `portfolio`.`fundManager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`tradingHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`tradingHistory` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`tradingHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL,
  `volume` INT NULL,
  `date` TIMESTAMP NULL,
  `fundManager_id` INT NOT NULL,
  `instrument_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TradingHistory_FundManager1_idx` (`fundManager_id` ASC),
  INDEX `fk_TradingHistory_Instrument1_idx` (`instrument_id` ASC),
  CONSTRAINT `fk_TradingHistory_FundManager1`
    FOREIGN KEY (`fundManager_id`)
    REFERENCES `portfolio`.`fundManager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TradingHistory_Instrument1`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `portfolio`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`historyPrice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`historyPrice` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`historyPrice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL,
  `high` FLOAT NULL,
  `low` FLOAT NULL,
  `date` TIMESTAMP NULL,
  `open` FLOAT NULL,
  `close` FLOAT NULL,
  `changed` FLOAT NULL,
  `instrument_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HistoryPrice_Instrument1_idx` (`instrument_id` ASC),
  CONSTRAINT `fk_HistoryPrice_Instrument1`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `portfolio`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`currentPrice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`currentPrice` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`currentPrice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL,
  `high` FLOAT NULL,
  `low` FLOAT NULL,
  `date` TIMESTAMP NULL,
  `open` FLOAT NULL,
  `close` FLOAT NULL,
  `changed` FLOAT NULL,
  `instrument_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CurrentPrice_Instrument1_idx` (`instrument_id` ASC),
  CONSTRAINT `fk_CurrentPrice_Instrument1`
    FOREIGN KEY (`instrument_id`)
    REFERENCES `portfolio`.`instrument` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
